import csv
import os

# Terminal Colors
C_CYAN = '\033[96m'
C_GREEN = '\033[92m'
C_YELLOW = '\033[93m'
C_RED = '\033[91m'
C_RESET = '\033[0m'

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
os.chdir(SCRIPT_DIR)

NODE_CSV = "TaxiNodes.csv"
PATH_CSV = "TaxiPath.csv"
OUTPUT_LUA = "Odysseus_RoutingDB.lua"

def clean_node_name(raw_name):
    """Strips the sub-zone data to keep the database clean and lightweight."""
    if not raw_name:
        return "Unknown Node"
    # Converts "Tranquillien, Eversong Woods" into just "Tranquillien"
    return raw_name.split(',')[0].strip()

def build_routing_database():
    print(f"\n{C_CYAN}=== Odysseus Relational Routing Compiler ==={C_RESET}\n")

    if not os.path.exists(NODE_CSV) or not os.path.exists(PATH_CSV):
        print(f"{C_RED}[ERROR] Missing CSV files!{C_RESET} Please download TaxiNodes.csv and TaxiPath.csv from Wago.tools.")
        input("Press Enter to exit...")
        return

    # --- 1. PARSE NODES ---
    print(f"{C_YELLOW}[INFO] Parsing TaxiNodes.csv...{C_RESET}")
    nodes = {}
    try:
        with open(NODE_CSV, mode='r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Wago columns vary slightly by patch, but usually 'ID' and 'Name_lang'
                node_id_col = next((k for k in row.keys() if k.upper() == 'ID'), None)
                name_col = next((k for k in row.keys() if 'NAME_LANG' in k.upper()), None)
                
                if node_id_col and name_col and row[node_id_col]:
                    nid = int(row[node_id_col])
                    name = clean_node_name(row[name_col])
                    # Skip developer test nodes
                    if "QA" not in name.upper() and "TEST" not in name.upper():
                        nodes[nid] = name
        print(f"{C_GREEN}[+] Loaded {len(nodes)} clean locations.{C_RESET}")
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to read nodes: {e}{C_RESET}")
        return

    # --- 2. PARSE PATHS (EDGES) ---
    print(f"{C_YELLOW}[INFO] Parsing TaxiPath.csv...{C_RESET}")
    routes = {}
    path_count = 0
    try:
        with open(PATH_CSV, mode='r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            for row in reader:
                from_col = next((k for k in row.keys() if 'FROMTAXINODE' in k.upper()), None)
                to_col = next((k for k in row.keys() if 'TOTAXINODE' in k.upper()), None)
                cost_col = next((k for k in row.keys() if 'COST' in k.upper()), None)

                if from_col and to_col and row[from_col] and row[to_col]:
                    from_id = int(row[from_col])
                    to_id = int(row[to_col])
                    cost = int(row[cost_col]) if cost_col and row[cost_col] else 0

                    # Only save paths where we know both node names
                    if from_id in nodes and to_id in nodes:
                        if from_id not in routes:
                            routes[from_id] = {}
                        routes[from_id][to_id] = cost
                        path_count += 1
        print(f"{C_GREEN}[+] Mapped {path_count} direct flight connections.{C_RESET}")
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to read paths: {e}{C_RESET}")
        return

    # --- 3. WRITE LUA DATABASE ---
    print(f"\n{C_YELLOW}[INFO] Compiling {OUTPUT_LUA}...{C_RESET}")
    try:
        with open(OUTPUT_LUA, "w", encoding="utf-8") as f:
            f.write('-- Auto-Generated by Odysseus Routing Compiler\n')
            f.write('local addonName, OUS = ...\n\n')
            
            # Write Nodes
            f.write('OUS.TaxiNodes = {\n')
            for nid, name in sorted(nodes.items()):
                safe_name = name.replace('"', '\\"')
                f.write(f'    [{nid}] = "{safe_name}",\n')
            f.write('}\n\n')

            # Write Routes
            f.write('OUS.TaxiRoutes = {\n')
            for from_id in sorted(routes.keys()):
                f.write(f'    [{from_id}] = {{\n')
                for to_id, cost in sorted(routes[from_id].items()):
                    f.write(f'        [{to_id}] = {{ cost = {cost} }},\n')
                f.write('    },\n')
            f.write('}\n')
            
        print(f"{C_GREEN}[SUCCESS] Relational Geography Database created!{C_RESET}")
        input("Press Enter to exit...")
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to write Lua file: {e}{C_RESET}")

if __name__ == "__main__":
    build_routing_database()