import csv
import os
import time

# --- TERMINAL COLORS ---
C_CYAN = '\033[96m'
C_GREEN = '\033[92m'
C_YELLOW = '\033[93m'
C_RED = '\033[91m'
C_PURPLE = '\033[95m'
C_RESET = '\033[0m'

FACTION_CSV = "Faction.csv"
PARAGON_CSV = "ParagonReputation.csv"
OUTPUT_FILE = "xpbar_data.lua"

# THE FIX: Set this to True to grab Stormwind, Ironforge, and every other valid faction!
SCRAPE_ALL = True 
TARGET_FACTIONS = [2590, 2594, 2570, 2563, 2503]

def compile_lua_data():
    print(f"{C_CYAN}=================================================={C_RESET}")
    print(f"{C_PURPLE}   Odysseus Multi-Table Faction Compiler...{C_RESET}")
    print(f"{C_CYAN}=================================================={C_RESET}\n")

    if not os.path.exists(FACTION_CSV) or not os.path.exists(PARAGON_CSV):
        print(f"{C_RED}[ERROR] Missing CSV files!{C_RESET}")
        print(f"{C_YELLOW}Ensure both '{FACTION_CSV}' and '{PARAGON_CSV}' are in this directory.{C_RESET}")
        input("Press Enter to exit...")
        return

    # --- STEP 1: PARSE PARAGON DATA ---
    print(f"{C_YELLOW}[INFO] Analyzing {PARAGON_CSV}...{C_RESET}")
    paragon_data = {}
    
    try:
        with open(PARAGON_CSV, mode='r', encoding='utf-8-sig') as p_file:
            reader = csv.DictReader(p_file)
            for row in reader:
                fac_id_col = next((k for k in row.keys() if 'FACTIONID' in k.upper()), None)
                thresh_col = next((k for k in row.keys() if 'LEVELTHRESHOLD' in k.upper()), None)
                quest_col = next((k for k in row.keys() if 'QUESTID' in k.upper()), None)

                if fac_id_col and row[fac_id_col]:
                    fid = int(row[fac_id_col])
                    paragon_data[fid] = {
                        "threshold": int(row[thresh_col]) if thresh_col and row[thresh_col] else 0,
                        "questID": int(row[quest_col]) if quest_col and row[quest_col] else 0
                    }
        print(f"{C_GREEN}[+] Mapped {len(paragon_data)} Paragon entries.{C_RESET}\n")
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to parse Paragon CSV: {e}{C_RESET}")
        input("Press Enter to exit...")
        return

# --- STEP 2: PARSE FACTION DATA ---
    print(f"{C_YELLOW}[INFO] Analyzing {FACTION_CSV} and merging data...{C_RESET}")
    faction_data = {}
    
    # Add a filter to drop Blizzard's developer garbage
    forbidden_words = ["UNUSED", "REUSE", "DO NOT USE", "DEPRECATED", "TRASH", "QA ", "TEST"]

    try:
        with open(FACTION_CSV, mode='r', encoding='utf-8-sig') as f_file:
            reader = csv.DictReader(f_file)
            for row in reader:
                id_col = next((k for k in row.keys() if k.upper() == 'ID'), None)
                name_col = next((k for k in row.keys() if 'NAME_LANG' in k.upper() or 'NAME' in k.upper()), None)

                if id_col and row[id_col]:
                    fid = int(row[id_col])
                    name = row[name_col] if name_col and row[name_col] else ""
                    
                    # Check if the name contains any of the forbidden developer words
                    is_valid_name = True
                    for word in forbidden_words:
                        if word in name.upper():
                            is_valid_name = False
                            break
                    
                    # Only save if it has a real name AND isn't garbage
                    if name != "" and is_valid_name and (SCRAPE_ALL or fid in TARGET_FACTIONS or fid in paragon_data):
                        faction_data[fid] = {
                            "name": name,
                            "paragon": paragon_data.get(fid, None)
                        }
                        print(f"{C_GREEN}[+] Processed Faction:{C_RESET} {fid} - {name}")
                        time.sleep(0.005) # Fast terminal scroll effect
                        
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to parse Faction CSV: {e}{C_RESET}")
        input("Press Enter to exit...")
        return

    # --- STEP 3: WRITE LUA FILE ---
    print(f"\n{C_YELLOW}[INFO] Compiling {OUTPUT_FILE}...{C_RESET}")
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write('-- Auto-Generated by Odysseus Multi-Table Compiler\n')
            f.write('local addonName, OUS = ...\n\n')
            f.write('OUS.FactionData = {\n')
            
            for fid, data in sorted(faction_data.items()):
                safe_name = data["name"].replace('"', '\\"')
                f.write(f'    [{fid}] = {{\n')
                f.write(f'        name = "{safe_name}",\n')
                
                if data["paragon"]:
                    f.write(f'        isParagon = true,\n')
                    f.write(f'        paragonThreshold = {data["paragon"]["threshold"]},\n')
                    f.write(f'        paragonQuestID = {data["paragon"]["questID"]},\n')
                else:
                    f.write(f'        isParagon = false,\n')
                
                f.write(f'        rewardNPC = {{ mapID = 0, x = 0.0, y = 0.0 }},\n') 
                f.write(f'    }},\n')
                
            f.write('}\n')
        
        print(f"{C_GREEN}[SUCCESS] {len(faction_data)} Factions successfully compiled to {OUTPUT_FILE}!{C_RESET}")
        input("Press Enter to exit...")
        
    except Exception as e:
        print(f"{C_RED}[ERROR] Failed to write Lua file: {e}{C_RESET}")
        input("Press Enter to exit...")

if __name__ == "__main__":
    compile_lua_data()