-- ==========================================
-- ODYSSEUS AUTO-GENERATED FACTION DATABASE
-- ==========================================
local addonName, OUS = ...

OUS.FactionData = {
    [1828] = {
        name = "Highmountain Tribe",
        isParagon = true,
        paragonFactionID = 2085,
        paragonThreshold = 10000,
        paragonQuestID = 46743,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [1859] = {
        name = "The Nightfallen",
        isParagon = true,
        paragonFactionID = 2089,
        paragonThreshold = 10000,
        paragonQuestID = 46748,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [1883] = {
        name = "Dreamweavers",
        isParagon = true,
        paragonFactionID = 2088,
        paragonThreshold = 10000,
        paragonQuestID = 46747,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [1894] = {
        name = "The Wardens",
        isParagon = true,
        paragonFactionID = 2090,
        paragonThreshold = 10000,
        paragonQuestID = 46749,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [1900] = {
        name = "Court of Farondis",
        isParagon = true,
        paragonFactionID = 2087,
        paragonThreshold = 10000,
        paragonQuestID = 46745,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [1948] = {
        name = "Valarjar",
        isParagon = true,
        paragonFactionID = 2086,
        paragonThreshold = 10000,
        paragonQuestID = 46746,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2045] = {
        name = "Armies of Legionfall",
        isParagon = true,
        paragonFactionID = 2091,
        paragonThreshold = 10000,
        paragonQuestID = 46777,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2085] = {
        name = "Highmountain Tribe (Paragon)",
        isParagon = true,
        paragonFactionID = 2085,
        paragonThreshold = 10000,
        paragonQuestID = 46743,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2086] = {
        name = "Valarjar (Paragon)",
        isParagon = true,
        paragonFactionID = 2086,
        paragonThreshold = 10000,
        paragonQuestID = 46746,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2087] = {
        name = "Court of Farondis (Paragon)",
        isParagon = true,
        paragonFactionID = 2087,
        paragonThreshold = 10000,
        paragonQuestID = 46745,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2088] = {
        name = "Dreamweavers (Paragon)",
        isParagon = true,
        paragonFactionID = 2088,
        paragonThreshold = 10000,
        paragonQuestID = 46747,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2089] = {
        name = "The Nightfallen (Paragon)",
        isParagon = true,
        paragonFactionID = 2089,
        paragonThreshold = 10000,
        paragonQuestID = 46748,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2090] = {
        name = "The Wardens (Paragon)",
        isParagon = true,
        paragonFactionID = 2090,
        paragonThreshold = 10000,
        paragonQuestID = 46749,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2091] = {
        name = "Armies of Legionfall (Paragon)",
        isParagon = true,
        paragonFactionID = 2091,
        paragonThreshold = 10000,
        paragonQuestID = 46777,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2103] = {
        name = "Zandalari Empire",
        isParagon = true,
        paragonFactionID = 2378,
        paragonThreshold = 10000,
        paragonQuestID = 54462,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2156] = {
        name = "Talanji's Expedition",
        isParagon = true,
        paragonFactionID = 2380,
        paragonThreshold = 10000,
        paragonQuestID = 54460,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2157] = {
        name = "The Honorbound",
        isParagon = true,
        paragonFactionID = 2385,
        paragonThreshold = 10000,
        paragonQuestID = 54455,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2158] = {
        name = "Voldunai",
        isParagon = true,
        paragonFactionID = 2382,
        paragonThreshold = 10000,
        paragonQuestID = 54461,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2159] = {
        name = "7th Legion",
        isParagon = true,
        paragonFactionID = 2384,
        paragonThreshold = 10000,
        paragonQuestID = 54454,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2160] = {
        name = "Proudmoore Admiralty",
        isParagon = true,
        paragonFactionID = 2379,
        paragonThreshold = 10000,
        paragonQuestID = 54458,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2161] = {
        name = "Order of Embers",
        isParagon = true,
        paragonFactionID = 2383,
        paragonThreshold = 10000,
        paragonQuestID = 54456,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2162] = {
        name = "Storm's Wake",
        isParagon = true,
        paragonFactionID = 2381,
        paragonThreshold = 10000,
        paragonQuestID = 54457,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2163] = {
        name = "Tortollan Seekers",
        isParagon = true,
        paragonFactionID = 2387,
        paragonThreshold = 10000,
        paragonQuestID = 54451,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2164] = {
        name = "Champions of Azeroth",
        isParagon = true,
        paragonFactionID = 2386,
        paragonThreshold = 10000,
        paragonQuestID = 54453,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2165] = {
        name = "Army of the Light",
        isParagon = true,
        paragonFactionID = 2166,
        paragonThreshold = 10000,
        paragonQuestID = 48977,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2166] = {
        name = "Army of the Light (Paragon)",
        isParagon = true,
        paragonFactionID = 2166,
        paragonThreshold = 10000,
        paragonQuestID = 48977,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2167] = {
        name = "Argussian Reach (Paragon)",
        isParagon = true,
        paragonFactionID = 2167,
        paragonThreshold = 10000,
        paragonQuestID = 48976,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2170] = {
        name = "Argussian Reach",
        isParagon = true,
        paragonFactionID = 2167,
        paragonThreshold = 10000,
        paragonQuestID = 48976,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2373] = {
        name = "The Unshackled",
        isParagon = true,
        paragonFactionID = 2374,
        paragonThreshold = 10000,
        paragonQuestID = 53982,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2374] = {
        name = "The Unshackled (Paragon)",
        isParagon = true,
        paragonFactionID = 2374,
        paragonThreshold = 10000,
        paragonQuestID = 53982,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2378] = {
        name = "Zandalari Empire (Paragon)",
        isParagon = true,
        paragonFactionID = 2378,
        paragonThreshold = 10000,
        paragonQuestID = 54462,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2379] = {
        name = "Proudmoore Admiralty (Paragon)",
        isParagon = true,
        paragonFactionID = 2379,
        paragonThreshold = 10000,
        paragonQuestID = 54458,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2380] = {
        name = "Talanji's Expedition (Paragon)",
        isParagon = true,
        paragonFactionID = 2380,
        paragonThreshold = 10000,
        paragonQuestID = 54460,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2381] = {
        name = "Storm's Wake (Paragon)",
        isParagon = true,
        paragonFactionID = 2381,
        paragonThreshold = 10000,
        paragonQuestID = 54457,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2382] = {
        name = "Voldunai (Paragon)",
        isParagon = true,
        paragonFactionID = 2382,
        paragonThreshold = 10000,
        paragonQuestID = 54461,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2383] = {
        name = "Order of Embers (Paragon)",
        isParagon = true,
        paragonFactionID = 2383,
        paragonThreshold = 10000,
        paragonQuestID = 54456,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2384] = {
        name = "7th Legion (Paragon)",
        isParagon = true,
        paragonFactionID = 2384,
        paragonThreshold = 10000,
        paragonQuestID = 54454,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2385] = {
        name = "The Honorbound (Paragon)",
        isParagon = true,
        paragonFactionID = 2385,
        paragonThreshold = 10000,
        paragonQuestID = 54455,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2386] = {
        name = "Champions of Azeroth (Paragon)",
        isParagon = true,
        paragonFactionID = 2386,
        paragonThreshold = 10000,
        paragonQuestID = 54453,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2387] = {
        name = "Tortollan Seekers (Paragon)",
        isParagon = true,
        paragonFactionID = 2387,
        paragonThreshold = 10000,
        paragonQuestID = 54451,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2391] = {
        name = "Rustbolt Resistance",
        isParagon = true,
        paragonFactionID = 2392,
        paragonThreshold = 10000,
        paragonQuestID = 55348,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2392] = {
        name = "Rustbolt Resistance (Paragon)",
        isParagon = true,
        paragonFactionID = 2392,
        paragonThreshold = 10000,
        paragonQuestID = 55348,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2400] = {
        name = "Waveblade Ankoan",
        isParagon = true,
        paragonFactionID = 2401,
        paragonThreshold = 10000,
        paragonQuestID = 55976,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2401] = {
        name = "Waveblade Ankoan (Paragon)",
        isParagon = true,
        paragonFactionID = 2401,
        paragonThreshold = 10000,
        paragonQuestID = 55976,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2407] = {
        name = "The Ascended",
        isParagon = true,
        paragonFactionID = 2441,
        paragonThreshold = 10000,
        paragonQuestID = 61097,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2410] = {
        name = "The Undying Army",
        isParagon = true,
        paragonFactionID = 2440,
        paragonThreshold = 10000,
        paragonQuestID = 61095,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2413] = {
        name = "Court of Harvesters",
        isParagon = true,
        paragonFactionID = 2442,
        paragonThreshold = 10000,
        paragonQuestID = 61100,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2415] = {
        name = "Rajani",
        isParagon = true,
        paragonFactionID = 2416,
        paragonThreshold = 10000,
        paragonQuestID = 58096,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2416] = {
        name = "Rajani (Paragon)",
        isParagon = true,
        paragonFactionID = 2416,
        paragonThreshold = 10000,
        paragonQuestID = 58096,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2417] = {
        name = "Uldum Accord",
        isParagon = true,
        paragonFactionID = 2418,
        paragonThreshold = 10000,
        paragonQuestID = 58097,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2418] = {
        name = "Uldum Accord (Paragon)",
        isParagon = true,
        paragonFactionID = 2418,
        paragonThreshold = 10000,
        paragonQuestID = 58097,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2432] = {
        name = "Ve'nari",
        isParagon = true,
        paragonFactionID = 2474,
        paragonThreshold = 10000,
        paragonQuestID = 64267,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2440] = {
        name = "The Undying Army (Paragon)",
        isParagon = true,
        paragonFactionID = 2440,
        paragonThreshold = 10000,
        paragonQuestID = 61095,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2441] = {
        name = "The Ascended (Paragon)",
        isParagon = true,
        paragonFactionID = 2441,
        paragonThreshold = 10000,
        paragonQuestID = 61097,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2442] = {
        name = "Court of Harvesters (Paragon)",
        isParagon = true,
        paragonFactionID = 2442,
        paragonThreshold = 10000,
        paragonQuestID = 61100,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2444] = {
        name = "The Wild Hunt (Paragon)",
        isParagon = true,
        paragonFactionID = 2444,
        paragonThreshold = 10000,
        paragonQuestID = 61098,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2465] = {
        name = "The Wild Hunt",
        isParagon = true,
        paragonFactionID = 2444,
        paragonThreshold = 10000,
        paragonQuestID = 61098,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2470] = {
        name = "Death's Advance",
        isParagon = true,
        paragonFactionID = 2471,
        paragonThreshold = 10000,
        paragonQuestID = 64012,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2471] = {
        name = "Death's Advance (Paragon)",
        isParagon = true,
        paragonFactionID = 2471,
        paragonThreshold = 10000,
        paragonQuestID = 64012,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2472] = {
        name = "The Archivists' Codex",
        isParagon = true,
        paragonFactionID = 2473,
        paragonThreshold = 10000,
        paragonQuestID = 64266,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2473] = {
        name = "The Archivists' Codex (Paragon)",
        isParagon = true,
        paragonFactionID = 2473,
        paragonThreshold = 10000,
        paragonQuestID = 64266,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2474] = {
        name = "Ve'nari (Paragon)",
        isParagon = true,
        paragonFactionID = 2474,
        paragonThreshold = 10000,
        paragonQuestID = 64267,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2478] = {
        name = "The Enlightened",
        isParagon = true,
        paragonFactionID = 2479,
        paragonThreshold = 10000,
        paragonQuestID = 64867,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2479] = {
        name = "The Enlightened (Paragon)",
        isParagon = true,
        paragonFactionID = 2479,
        paragonThreshold = 10000,
        paragonQuestID = 64867,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2503] = {
        name = "Maruuk Centaur",
        isParagon = true,
        paragonFactionID = 2504,
        paragonThreshold = 7500,
        paragonQuestID = 65606,
        rewardNPC = { mapID = 2025, x = 47.1, y = 82.6, npcName = "Cataloger Jakes" },
    },
    [2504] = {
        name = "Maruuk Centaur (Paragon)",
        isParagon = true,
        paragonFactionID = 2504,
        paragonThreshold = 7500,
        paragonQuestID = 65606,
        rewardNPC = { mapID = 2025, x = 47.1, y = 82.6, npcName = "Cataloger Jakes" },
    },
    [2507] = {
        name = "Dragonscale Expedition",
        isParagon = true,
        paragonFactionID = 2508,
        paragonThreshold = 7500,
        paragonQuestID = 66156,
        rewardNPC = { mapID = 2112, x = 31, y = 61.8, npcName = "Sorotis" },
    },
    [2508] = {
        name = "Dragonscale Expedition (Paragon)",
        isParagon = true,
        paragonFactionID = 2508,
        paragonThreshold = 7500,
        paragonQuestID = 66156,
        rewardNPC = { mapID = 2112, x = 31, y = 61.8, npcName = "Sorotis" },
    },
    [2510] = {
        name = "Valdrakken Accord",
        isParagon = true,
        paragonFactionID = 2552,
        paragonThreshold = 7500,
        paragonQuestID = 71023,
        rewardNPC = { mapID = 2112, x = 58.9, y = 38.3, npcName = "Tattukiaka" },
    },
    [2511] = {
        name = "Iskaara Tuskarr",
        isParagon = true,
        paragonFactionID = 2551,
        paragonThreshold = 7500,
        paragonQuestID = 66511,
        rewardNPC = { mapID = 2023, x = 64.1, y = 41, npcName = "Quartermaster Huseng" },
    },
    [2517] = {
        name = "Wrathion",
        isParagon = false,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2518] = {
        name = "Sabellian",
        isParagon = false,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2521] = {
        name = "Clan Nokhud (Paragon)",
        isParagon = true,
        paragonFactionID = 2521,
        paragonThreshold = 10000,
        paragonQuestID = 0,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2526] = {
        name = "Winterpelt Furbolg",
        isParagon = false,
        rewardNPC = { mapID = 2024, x = 65.6, y = 36, npcName = "Sonovo" },
    },
    [2544] = {
        name = "Artisan's Consortium - Dragon Isles Branch",
        isParagon = false,
        rewardNPC = { mapID = 2022, x = 35.6, y = 59.2, npcName = "Rabul" },
    },
    [2550] = {
        name = "Cobalt Assembly",
        isParagon = false,
        rewardNPC = { mapID = 2025, x = 61.5, y = 50.9, npcName = "Soridormi" },
    },
    [2551] = {
        name = "Iskaara Tuskarr (Paragon)",
        isParagon = true,
        paragonFactionID = 2551,
        paragonThreshold = 7500,
        paragonQuestID = 66511,
        rewardNPC = { mapID = 2023, x = 64.1, y = 41, npcName = "Quartermaster Huseng" },
    },
    [2552] = {
        name = "Valdrakken Accord (Paragon)",
        isParagon = true,
        paragonFactionID = 2552,
        paragonThreshold = 7500,
        paragonQuestID = 71023,
        rewardNPC = { mapID = 2112, x = 58.9, y = 38.3, npcName = "Tattukiaka" },
    },
    [2564] = {
        name = "Loamm Niffen",
        isParagon = true,
        paragonFactionID = 2565,
        paragonThreshold = 7500,
        paragonQuestID = 75290,
        rewardNPC = { mapID = 2133, x = 55.7, y = 55.5, npcName = "Ponzo" },
    },
    [2565] = {
        name = "Loamm Niffen (Paragon)",
        isParagon = true,
        paragonFactionID = 2565,
        paragonThreshold = 7500,
        paragonQuestID = 75290,
        rewardNPC = { mapID = 2133, x = 55.7, y = 55.5, npcName = "Ponzo" },
    },
    [2570] = {
        name = "Hallowfall Arathi",
        isParagon = true,
        paragonFactionID = 2611,
        paragonThreshold = 7500,
        paragonQuestID = 79218,
        rewardNPC = { mapID = 2215, x = 41.3, y = 53.1, npcName = "Auralia Steelstrike" },
    },
    [2574] = {
        name = "Dream Wardens",
        isParagon = true,
        paragonFactionID = 2575,
        paragonThreshold = 7500,
        paragonQuestID = 76425,
        rewardNPC = { mapID = 2200, x = 49.8, y = 62.2, npcName = "Pipsee" },
    },
    [2575] = {
        name = "Dream Wardens (Paragon)",
        isParagon = true,
        paragonFactionID = 2575,
        paragonThreshold = 7500,
        paragonQuestID = 76425,
        rewardNPC = { mapID = 2200, x = 49.8, y = 62.2, npcName = "Pipsee" },
    },
    [2590] = {
        name = "Council of Dornogal",
        isParagon = true,
        paragonFactionID = 2612,
        paragonThreshold = 7500,
        paragonQuestID = 79219,
        rewardNPC = { mapID = 2339, x = 39.1, y = 24.2, npcName = "Auditor Balwurz" },
    },
    [2594] = {
        name = "The Assembly of the Deeps",
        isParagon = true,
        paragonFactionID = 2613,
        paragonThreshold = 7500,
        paragonQuestID = 79220,
        rewardNPC = { mapID = 2214, x = 47.3, y = 32.9, npcName = "Waxmonger Squick" },
    },
    [2596] = {
        name = "The Severed Threads (Paragon)",
        isParagon = true,
        paragonFactionID = 2596,
        paragonThreshold = 7500,
        paragonQuestID = 79196,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2600] = {
        name = "The Severed Threads",
        isParagon = true,
        paragonFactionID = 2596,
        paragonThreshold = 7500,
        paragonQuestID = 79196,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2601] = {
        name = "The Weaver",
        isParagon = true,
        paragonFactionID = 2648,
        paragonThreshold = 2500,
        paragonQuestID = 83738,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2604] = {
        name = "Keg Leg's Crew (Paragon)",
        isParagon = true,
        paragonFactionID = 2604,
        paragonThreshold = 10000,
        paragonQuestID = 0,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2605] = {
        name = "The General",
        isParagon = true,
        paragonFactionID = 2649,
        paragonThreshold = 2500,
        paragonQuestID = 83739,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2607] = {
        name = "The Vizier",
        isParagon = true,
        paragonFactionID = 2647,
        paragonThreshold = 2500,
        paragonQuestID = 83740,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2611] = {
        name = "Hallowfall Arathi (Paragon)",
        isParagon = true,
        paragonFactionID = 2611,
        paragonThreshold = 7500,
        paragonQuestID = 79218,
        rewardNPC = { mapID = 2215, x = 41.3, y = 53.1, npcName = "Auralia Steelstrike" },
    },
    [2612] = {
        name = "Council of Dornogal (Paragon)",
        isParagon = true,
        paragonFactionID = 2612,
        paragonThreshold = 7500,
        paragonQuestID = 79219,
        rewardNPC = { mapID = 2339, x = 39.1, y = 24.2, npcName = "Auditor Balwurz" },
    },
    [2613] = {
        name = "The Assembly of the Deeps (Paragon)",
        isParagon = true,
        paragonFactionID = 2613,
        paragonThreshold = 7500,
        paragonQuestID = 79220,
        rewardNPC = { mapID = 2214, x = 47.3, y = 32.9, npcName = "Waxmonger Squick" },
    },
    [2616] = {
        name = "Keg Leg Thrasher",
        isParagon = true,
        paragonFactionID = 2604,
        paragonThreshold = 10000,
        paragonQuestID = 0,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2647] = {
        name = "The Vizier (Paragon)",
        isParagon = true,
        paragonFactionID = 2647,
        paragonThreshold = 2500,
        paragonQuestID = 83740,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2648] = {
        name = "The Weaver (Paragon)",
        isParagon = true,
        paragonFactionID = 2648,
        paragonThreshold = 2500,
        paragonQuestID = 83738,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2649] = {
        name = "The General (Paragon)",
        isParagon = true,
        paragonFactionID = 2649,
        paragonThreshold = 2500,
        paragonQuestID = 83739,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2653] = {
        name = "The Cartels of Undermine",
        isParagon = true,
        paragonFactionID = 2667,
        paragonThreshold = 7500,
        paragonQuestID = 85805,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2658] = {
        name = "The K'aresh Trust",
        isParagon = true,
        paragonFactionID = 2659,
        paragonThreshold = 7500,
        paragonQuestID = 85109,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2659] = {
        name = "The K'aresh Trust (Paragon)",
        isParagon = true,
        paragonFactionID = 2659,
        paragonThreshold = 7500,
        paragonQuestID = 85109,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2667] = {
        name = "The Cartels of Undermine (Paragon)",
        isParagon = true,
        paragonFactionID = 2667,
        paragonThreshold = 7500,
        paragonQuestID = 85805,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2668] = {
        name = "Darkfuse Solutions (Paragon)",
        isParagon = true,
        paragonFactionID = 2668,
        paragonThreshold = 10000,
        paragonQuestID = 85808,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2669] = {
        name = "Darkfuse Solutions",
        isParagon = true,
        paragonFactionID = 2668,
        paragonThreshold = 10000,
        paragonQuestID = 85808,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2670] = {
        name = "Venture Company (Paragon)",
        isParagon = true,
        paragonFactionID = 2670,
        paragonThreshold = 10000,
        paragonQuestID = 85810,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2671] = {
        name = "Venture Company",
        isParagon = true,
        paragonFactionID = 2670,
        paragonThreshold = 10000,
        paragonQuestID = 85810,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2672] = {
        name = "Bilgewater Cartel (Paragon)",
        isParagon = true,
        paragonFactionID = 2672,
        paragonThreshold = 10000,
        paragonQuestID = 85806,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2673] = {
        name = "Bilgewater Cartel",
        isParagon = true,
        paragonFactionID = 2672,
        paragonThreshold = 10000,
        paragonQuestID = 85806,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2674] = {
        name = "Blackwater Cartel (Paragon)",
        isParagon = true,
        paragonFactionID = 2674,
        paragonThreshold = 10000,
        paragonQuestID = 85807,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2675] = {
        name = "Blackwater Cartel",
        isParagon = true,
        paragonFactionID = 2674,
        paragonThreshold = 10000,
        paragonQuestID = 85807,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2676] = {
        name = "Steamwheedle Cartel (Paragon)",
        isParagon = true,
        paragonFactionID = 2676,
        paragonThreshold = 10000,
        paragonQuestID = 85809,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2677] = {
        name = "Steamwheedle Cartel",
        isParagon = true,
        paragonFactionID = 2676,
        paragonThreshold = 10000,
        paragonQuestID = 85809,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2684] = {
        name = "Gallagio Loyalty Rewards Club (Paragon)",
        isParagon = true,
        paragonFactionID = 2684,
        paragonThreshold = 7500,
        paragonQuestID = 85471,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2685] = {
        name = "Gallagio Loyalty Rewards Club",
        isParagon = true,
        paragonFactionID = 2684,
        paragonThreshold = 7500,
        paragonQuestID = 85471,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2688] = {
        name = "Flame's Radiance",
        isParagon = true,
        paragonFactionID = 2689,
        paragonThreshold = 7500,
        paragonQuestID = 89515,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2689] = {
        name = "Flame's Radiance (Paragon)",
        isParagon = true,
        paragonFactionID = 2689,
        paragonThreshold = 7500,
        paragonQuestID = 89515,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2696] = {
        name = "Amani Tribe",
        isParagon = true,
        paragonFactionID = 2705,
        paragonThreshold = 7500,
        paragonQuestID = 93566,
        rewardNPC = { mapID = 2437, x = 45.9, y = 65.9, npcName = "Magovu" },
    },
    [2699] = {
        name = "The Singularity",
        isParagon = true,
        paragonFactionID = 2725,
        paragonThreshold = 7500,
        paragonQuestID = 89032,
        rewardNPC = { mapID = 2405, x = 52.5, y = 72.9, npcName = "Void Researcher Anomander" },
    },
    [2704] = {
        name = "Hara'ti",
        isParagon = true,
        paragonFactionID = 2726,
        paragonThreshold = 7500,
        paragonQuestID = 89035,
        rewardNPC = { mapID = 2413, x = 51, y = 50.8, npcName = "Naynar" },
    },
    [2705] = {
        name = "Amani Tribe (Paragon)",
        isParagon = true,
        paragonFactionID = 2705,
        paragonThreshold = 7500,
        paragonQuestID = 93566,
        rewardNPC = { mapID = 2437, x = 45.9, y = 65.9, npcName = "Magovu" },
    },
    [2710] = {
        name = "Silvermoon Court",
        isParagon = true,
        paragonFactionID = 2727,
        paragonThreshold = 7500,
        paragonQuestID = 93811,
        rewardNPC = { mapID = 2395, x = 43.4, y = 47.4, npcName = "Caeris Fairdawn" },
    },
    [2725] = {
        name = "The Singularity (Paragon)",
        isParagon = true,
        paragonFactionID = 2725,
        paragonThreshold = 7500,
        paragonQuestID = 89032,
        rewardNPC = { mapID = 2405, x = 52.5, y = 72.9, npcName = "Void Researcher Anomander" },
    },
    [2726] = {
        name = "Hara'ti (Paragon)",
        isParagon = true,
        paragonFactionID = 2726,
        paragonThreshold = 7500,
        paragonQuestID = 89035,
        rewardNPC = { mapID = 2413, x = 51, y = 50.8, npcName = "Naynar" },
    },
    [2727] = {
        name = "Silvermoon Court (Paragon)",
        isParagon = true,
        paragonFactionID = 2727,
        paragonThreshold = 7500,
        paragonQuestID = 93811,
        rewardNPC = { mapID = 2395, x = 43.4, y = 47.4, npcName = "Caeris Fairdawn" },
    },
    [2764] = {
        name = "Prey: Season 1",
        isParagon = false,
        rewardNPC = { mapID = 0, x = 0.0, y = 0.0, npcName = "" },
    },
    [2770] = {
        name = "Slayer's Duellum",
        isParagon = true,
        paragonFactionID = 2774,
        paragonThreshold = 10000,
        paragonQuestID = 94492,
        rewardNPC = { mapID = 2444, x = 39.3, y = 80.9, npcName = "Thraxadar" },
    },
    [2774] = {
        name = "Slayer's Duellum (Paragon)",
        isParagon = true,
        paragonFactionID = 2774,
        paragonThreshold = 10000,
        paragonQuestID = 94492,
        rewardNPC = { mapID = 2444, x = 39.3, y = 80.9, npcName = "Thraxadar" },
    },
}
